## Análisis de contagios identificados por COVID-19 en Colombia al 27/03/202

Fuente: Gobierno Nacional (datos disponibles en este [enlace](https://coronaviruscolombia.gov.co/Covid19/index.html)).
Por favor tener presente:
> Las cifras de contagios en los reportes oficiales **NO refleja la totalidad de contagios** en la población colombiana sino a una fracción menor, correspondiente a los **casos diagnosticados como positivos** en las pruebas de detección realizadas hasta la fecha.

In [81]:
import pandas as pd
import numpy as np
import datetime as dt

In [82]:
confirmed_cases = pd.read_csv("casos_03_27.csv")
confirmed_cases

,ID de caso,Fecha de diagnóstico,Ciudad de ubicación,Departamento,Atención,Edad,Sexo,Tipo*,País de procedencia
0,1,06/03/2020,Bogotá,Bogotá,Recuperado,10 a 19,F,Importado,Italia
1,2,09/03/2020,Buga,Valle,Recuperado,30 a 39,M,Importado,España
2,3,09/03/2020,Medellín,Antioquia,Recuperado,50 a 59,F,Importado,España
3,4,11/03/2020,Medellín,Antioquia,En casa,50 a 59,M,Relacionado,Colombia
4,5,11/03/2020,Medellín,Antioquia,Recuperado,20 a 29,M,Relacionado,Colombia
...,...,...,...,...,...,...,...,...,...
534,535,27/3/2020,Soledad,Atlántico,En casa,20 a 29,F,En estudio,Colombia
535,536,27/3/2020,Armenia,Quindío,En casa,40 a 49,F,Relacionado,Colombia
536,537,27/3/2020,Armenia,Quindío,En casa,30 a 39,F,Relacionado,Colombia
537,538,27/3/2020,Santa Marta,Santa Marta,En casa,60 a 69,F,Relacionado,Colombia
538,539,27/3/2020,Manizales,Caldas,En casa,80 a 89,M,Relacionado,Colombia

In [92]:
original_names = confirmed_cases.columns.to_list()
column_names = ['id','date','city','department','status','age','gender','origin','related_origin_country']
column_types = ['int','str','str','str','str','str','str','str','str']

df = ( confirmed_cases.copy()
      .astype(  dtype={k:v for k,v in zip(original_names, column_types)})
      .rename(columns={k:v for k,v in zip(original_names, column_names)})
     ).set_index('id')
df['date'] = pd.to_datetime(df['date'],dayfirst=True)
df.head()

,date,city,department,status,age,gender,origin,related_origin_country
id,,,,,,,,
1,2020-03-06,Bogotá,Bogotá,Recuperado,10 a 19,F,Importado,Italia
2,2020-03-09,Buga,Valle,Recuperado,30 a 39,M,Importado,España
3,2020-03-09,Medellín,Antioquia,Recuperado,50 a 59,F,Importado,España
4,2020-03-11,Medellín,Antioquia,En casa,50 a 59,M,Relacionado,Colombia
5,2020-03-11,Medellín,Antioquia,Recuperado,20 a 29,M,Relacionado,Colombia

In [112]:
df_daily = ( df.groupby(['date'])
            .apply(len)
            .reset_index()
            .rename(columns={0:'new_confirmed_daily'})
           )
df_daily['aggregate'] = pd.Series([df_daily['new_confirmed_daily'].iloc[:i+1].sum() for i in df_daily.index])

In [113]:
df_daily

         date  new_confirmed_daily  aggregate
0  2020-03-06                    1          1
1  2020-03-09                    2          3
2  2020-03-11                    6          9
3  2020-03-12                    4         13
4  2020-03-13                    3         16
5  2020-03-14                    8         24
6  2020-03-15                   21         45
7  2020-03-16                   12         57
8  2020-03-17                   18         75
9  2020-03-18                   27        102
10 2020-03-19                   26        128
11 2020-03-20                   47        175
12 2020-03-21                   35        210
13 2020-03-22                   30        240
14 2020-03-23                   66        306
15 2020-03-24                  113        419
16 2020-03-25                   62        481
17 2020-03-26                   10        491
18 2020-03-27                   48        539

In [114]:
import seaborn as sns
sns.set(style="darkgrid")
sns.lineplot(data=df_daily[['date','aggregate']])

TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64]